pool:
  vmImage: 'Ubuntu 16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Install Node.js'

- script: npm ci
  displayName: install dependencies

- script: npm run build
  displayName: transpile TypeScript

- script: npm test
  env:
    JEST_JUNIT_OUTPUT: junit.xml
  displayName: test and lint

- task: PublishTestResults@2
  inputs:
    testResultsFormat: JUnit
    testResultsFiles: junit.xml
  displayName: publish test results
