pool:
  vmImage: 'Ubuntu 16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Install Node.js'

- displayName: install dependencies
  script: npm ci

- displayName: transpile TypeScript
  script: npm run build

- displayName: test and lint
  script: npm test
  env:
    JEST_JUNIT_OUTPUT: junit.xml

- displayName: publish test results
  task: PublishTestResults@2
  inputs:
    testResultsFormat: JUnit
    testResultsFiles: junit.xml
